apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-mainroad
spec:
  displayName: Mainroad
  author:
    name: XRAYaksr
    website: https://github.com/XRAYaksr
  description: Hugo mainroad theme adapted for Halo
  logo: /themes/theme-mainroad/assets/images/favicon.png
  website: https://github.com/XRAYaksr/theme-mainroad
  repo: https://github.com/XRAYaksr/theme-mainroad.git
  settingName: "theme-mainroad-setting"
  configMapName: "theme-mainroad-configMap"
  version: 1.0.0
  require: ">=2.0.0"
